# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

baseurl: 
exclude: ['README.md', 'Gemfile']
permalink: "/novedades/:slug"

# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _scss

host: 192.168.1.26

collections:
  talleres:
    output: true
  agenda:
    output: true

paginate: 7
paginate_path: "/novedades/:num/"

livereload: true     # You no longer need to include --livereload